services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/app

  test:
    build:
      context: .
      target: test
    volumes:
      - .:/app
    command: bundle exec rake test
