contone_compression: none
bitonal_compression: none
shipment_class: Shipment
stages:
  - name: Preflight
    class: Preflight
    file: preflight
  - name: Image Validator
    class: ImageValidator
    file: image_validator
  - name: Pagination Check
    class: PaginationCheck
    file: pagination_check
  - name: Tagger
    class: Tagger
    file: tagger
  - name: GenerateChecksums
    class: GenerateChecksums
    file: generate_checksums
