contone_compression: jp2
bitonal_compression: g4
shipment_class: DLXSShipment
stages:
  - name: Preflight
    class: Preflight
    file: preflight
  - name: Image Validator
    class: ImageValidator
    file: image_validator
  - name: Pagination Check
    class: PaginationCheck
    file: pagination_check
  - name: Create Source Directory
    class: CreateSourceDirectory
    file: create_source_directory
  - name: Tagger
    class: Tagger
    file: tagger
  - name: Compression
    class: Compression
    file: compression
  - name: DLXSCompressor
    class: DLXSCompressor
    file: dlxs_compressor
  - name: Postflight
    class: Postflight
    file: postflight


